apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |-
    worker_processes auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;
        resolver 1.1.1.1;

        server {
            listen 80;

            root /var/www/html;

            location ~ ^/(.*) {
                proxy_pass http://127.0.0.1:8080/$1;
                proxy_set_header Authorization "Bearer am9objpodW50ZXIy";
                proxy_pass_header Authorization;
                proxy_set_header X-Test-Header "Hello world";
            }
        }
    }